repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff-check
      - id: ruff-format

  - repo: https://github.com/facebook/pyrefly-pre-commit
    rev: 0.47.0
    hooks:
      - id: pyrefly-check
        pass_filenames: false
        language: system