[tool.ruff]
src = ["backend", "executor", "executor_manager"]

[tool.pyrefly]

project-includes = [
    "backend",
    "executor",
    "executor_manager"
]

search_path = [
    "backend",
    "executor",
    "executor_manager"
]